"""HTML fragments generated by Python for the browser interface."""
from html import escape


def text(value):
    return escape(str(value if value is not None else ""), quote=True)


def poster(movie):
    title = str(movie.get("title") or "Sem título")
    image = movie.get("image")
    missing = not image or image in ("N/A", "poster-placeholder.svg")
    hue = sum(ord(char) for char in title) % 360
    cover = "" if missing else (
        f'<img src="{text(image)}" alt="Capa de {text(title)}" loading="lazy" '
        'decoding="async" width="300" height="450" referrerpolicy="no-referrer">')
    return (f'<div class="poster-art {"no-cover" if missing else ""}" style="--poster-hue:{hue}">'
            f'<div class="poster-lettering"><span class="poster-monogram" aria-hidden="true">{text(title[:1])}</span>'
            f'<small>CINEVERSE · {text(movie.get("type"))}</small><strong>{text(title)}</strong>'
            f'<span>{text(movie.get("year"))}</span><small>Capa indisponível</small></div>{cover}</div>')


def present(movie):
    identifier, title = text(movie["id"]), text(movie.get("title"))
    kind, year = text(movie.get("type")), text(movie.get("year"))
    genre, score = text(movie.get("genre")), text(movie.get("score"))
    art = poster(movie)
    meta = f'<span>{year}</span><span>{kind}</span><span>{genre}</span>'
    rating = (f'<span class="rating">★ {score} · '
              f'{text(movie.get("ratingSource") or movie.get("source") or "IMDb")}</span>')
    facts = [("Duração", movie.get("runtime") or "Não informada"),
             ("Elenco", ", ".join(movie.get("cast") or []) or "Não informado")]
    if movie.get("seasons"):
        facts.append(("Temporadas", movie["seasons"]))
    if movie.get("originalTitle") and movie["originalTitle"] != movie.get("title"):
        facts.append(("Título original", movie["originalTitle"]))
    return dict(movie, html={
        "poster": art,
        "meta": meta,
        "heroMeta": meta + (rating if movie.get("score") not in (None, "", "—") else ""),
        "detailMeta": rating + meta,
        "facts": "".join(f'<div><dt>{label}</dt><dd>{text(value)}</dd></div>' for label, value in facts),
        "card": (
            f'<article class="movie-card"><div class="poster" data-open="{identifier}" tabindex="0" '
            f'role="button" aria-label="Detalhes de {title}">{art}<span class="card-badge">{kind}</span>'
            f'<button class="save-button" data-save="{identifier}" aria-label="Salvar {title}" aria-pressed="false">+</button>'
            '<span class="play-hover" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"></circle>'
            '<path d="M12 11v5M12 8h.01"></path></svg></span></div>'
            f'<div class="card-info"><div class="card-title-row"><h3>{title}</h3>'
            f'<span class="score"><span>★</span> {score}</span></div><p>{year} · {genre}</p></div></article>'),
        "saved": (
            f'<article class="saved-card"><div class="saved-poster" data-open="{identifier}" tabindex="0" role="button">'
            f'{art}<button data-save="{identifier}" aria-label="Remover {title} da lista">×</button></div>'
            f'<h3>{title}</h3><p>{year} · {kind}</p></article>'),
    })


def catalog(data):
    return dict(data, items=[present(item) for item in data["items"]],
                featured=[present(item) for item in data.get("featured", [])],
                suggestionsHtml="".join(
                    f'<button type="button" data-suggestion="{text(title)}">{text(title)}</button>'
                    for title in data.get("suggestions", [])))
